name: Deploy master

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Hostinger deployment
        run: |
          curl -X POST https://webhooks.hostinger.com/deploy/5bcfe9433978980bdf3590a539a2bdde \
          -H "Content-Type: application/json" \
          -d '{}'

      - name: Wait for deployment to finish
        run: sleep 5

      - name: Clear cache
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 60s
          script: |
            cd ~/domains/staging.drankbestel.nl/public_html
            wp acorn optimize:clear
            wp acorn optimize
            wp litespeed-purge all
